name: one-shot release v0.1.2

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/one-shot-release-v0.1.2.yml"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ccd1f6ffba09937382becdff6ee283a08d3b8408
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./...

      - name: Build
        run: make dist VERSION="0.1.2"

      - name: Create v0.1.2 release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v0.1.2" \
            --target "ccd1f6ffba09937382becdff6ee283a08d3b8408" \
            --generate-notes \
            --title "v0.1.2" \
            bin/ns-apns-linux-amd64 \
            bin/ns-apns-linux-arm64
